# api/ingest_utils.py
import os
import json
from typing import List, Dict, Any

from api.evtx_parser import generate_evtx_derivatives
from api.registry_parser import generate_registry_derivatives
from api.embedder import embed_texts

TEXT_EXTENSIONS = {".txt", ".log", ".json", ".csv", ".md"}
REGISTRY_EXTENSIONS = {".dat", ".hiv", ".hive", ".reg"}

MAX_FILE_CHARS = int(os.getenv("MAX_FILE_CHARS", "20000"))
CHUNK_CHARS = int(os.getenv("CHUNK_CHARS", "1200"))
CHUNK_OVERLAP = int(os.getenv("CHUNK_OVERLAP", "150"))


def _chunk_text(text: str, max_chars: int = CHUNK_CHARS, overlap: int = CHUNK_OVERLAP) -> List[str]:
    text = (text or "").strip()
    if not text:
        return []
    if len(text) <= max_chars:
        return [text]

    out = []
    step = max(1, max_chars - overlap)
    for start in range(0, len(text), step):
        chunk = text[start : start + max_chars].strip()
        if chunk:
            out.append(chunk)
    return out


def _read_text_file(path: str) -> str:
    try:
        with open(path, "r", encoding="utf-8", errors="ignore") as f:
            return f.read(MAX_FILE_CHARS)
    except Exception:
        return ""


def build_and_index_case_corpus(case_dir: str, case_id: str) -> int:
    """
    Walk the case directory (prefer case_dir/files), convert EVTX + Registry → text,
    write summaries (evtx_summaries.jsonl / registry_summaries.jsonl),
    and push chunks into Chroma via embed_texts().

    Returns number of text chunks indexed.
    """
    text_chunks: List[str] = []
    metadata_list: List[Dict[str, Any]] = []

    # Prefer scanning extracted evidence in /files only (prevents feedback loops)
    scan_root = os.path.join(case_dir, "files")
    if not os.path.isdir(scan_root):
        scan_root = case_dir

    evtx_summary_path = os.path.join(case_dir, "evtx_summaries.jsonl")
    reg_summary_path = os.path.join(case_dir, "registry_summaries.jsonl")

    # Start clean for generated summary files
    with open(evtx_summary_path, "w", encoding="utf-8") as evtx_summary_f, \
         open(reg_summary_path, "w", encoding="utf-8") as reg_summary_f:

        for root, _, files in os.walk(scan_root):
            for filename in files:
                path = os.path.join(root, filename)
                ext = os.path.splitext(filename)[1].lower()
                rel_path = os.path.relpath(path, case_dir)

                # Skip our own outputs if scanning case_dir directly
                if filename in (
                    "evtx_summaries.jsonl",
                    "evtx_raw_summaries.jsonl",
                    "registry_summaries.jsonl",
                    "metadata.jsonl",
                ):
                    continue

                # 1) EVTX
                if ext == ".evtx":
                    stats = generate_evtx_derivatives(path, case_dir)
                    print(f"[EVTX] {filename}: {stats['events_count']} events parsed")

                    # Index the one-line summaries generated by evtx_parser
                    try:
                        with open(stats["txt_path"], "r", encoding="utf-8", errors="ignore") as f:
                            for line in f:
                                line = line.strip()
                                if not line:
                                    continue
                                text_chunks.append(line)
                                metadata_list.append({
                                    "source": "evtx",
                                    "case_id": case_id,
                                    "file": rel_path,
                                })
                                evtx_summary_f.write(line + "\n")
                    except Exception as e:
                        print(f"[EVTX] failed reading derivative txt for {filename}: {e}")

                # 2) Registry
                elif ext in REGISTRY_EXTENSIONS:
                    print(f"[REGISTRY] candidate: {filename}")
                    stats = generate_registry_derivatives(path, case_dir)
                    print(f"[REGISTRY] {filename}: {stats['events_count']} entries parsed")

                    if stats.get("events_count", 0) > 0:
                        try:
                            with open(stats["txt_path"], "r", encoding="utf-8", errors="ignore") as f:
                                for line in f:
                                    line = line.strip()
                                    if not line:
                                        continue
                                    text_chunks.append(line)
                                    metadata_list.append({
                                        "source": "registry",
                                        "case_id": case_id,
                                        "file": rel_path,
                                    })
                                    reg_summary_f.write(line + "\n")
                        except Exception as e:
                            print(f"[REGISTRY] failed reading derivative txt for {filename}: {e}")

                # 3) Normal text-like files
                elif ext in TEXT_EXTENSIONS:
                    content = _read_text_file(path)
                    if not content.strip():
                        continue

                    chunks = _chunk_text(content)
                    for idx, ch in enumerate(chunks):
                        text_chunks.append(ch)
                        metadata_list.append({
                            "source": "file",
                            "case_id": case_id,
                            "file": rel_path,
                            "chunk": idx,
                        })

    # ------------------------------------------------------------------
    # FALLBACK: rebuild evtx_summaries.jsonl if derivative summaries ended up empty
    # ------------------------------------------------------------------
    try:
        need_fallback = (not os.path.exists(evtx_summary_path)) or os.path.getsize(evtx_summary_path) == 0
        if need_fallback:
            print(f"[EVTX] summary fallback triggered for case={case_id}")
            evtx_art_dir = os.path.join(case_dir, "artifacts", "evtx")
            wrote_any = False

            # Fallback 1: rebuild from artifacts/evtx/*.txt
            if os.path.isdir(evtx_art_dir):
                with open(evtx_summary_path, "a", encoding="utf-8") as out_f:
                    for name in os.listdir(evtx_art_dir):
                        if not name.lower().endswith(".txt"):
                            continue
                        p = os.path.join(evtx_art_dir, name)
                        try:
                            with open(p, "r", encoding="utf-8", errors="ignore") as f:
                                for line in f:
                                    s = line.strip()
                                    if not s:
                                        continue
                                    out_f.write(s + "\n")
                                    text_chunks.append(s)
                                    metadata_list.append({
                                        "source": "evtx_fallback_txt",
                                        "case_id": case_id,
                                        "file": os.path.relpath(p, case_dir),
                                    })
                                    wrote_any = True
                        except Exception as e:
                            print(f"[EVTX] fallback txt read failed for {p}: {e}")

            # Fallback 2: rebuild from worker raw summaries if still empty
            raw_evtx_path = os.path.join(case_dir, "evtx_raw_summaries.jsonl")
            still_empty = (not os.path.exists(evtx_summary_path)) or os.path.getsize(evtx_summary_path) == 0

            if still_empty and os.path.exists(raw_evtx_path):
                print(f"[EVTX] raw-summary fallback triggered for case={case_id}")
                with open(raw_evtx_path, "r", encoding="utf-8", errors="ignore") as raw_f, \
                     open(evtx_summary_path, "a", encoding="utf-8") as out_f:
                    for line in raw_f:
                        line = line.strip()
                        if not line:
                            continue
                        try:
                            evt = json.loads(line)
                        except Exception:
                            continue

                        ts = evt.get("timestamp") or "UNKNOWN_TIME"
                        eid = evt.get("event_id")
                        rec = evt.get("record_num")
                        file_name = evt.get("file") or ""
                        xml_snippet = (evt.get("xml_snippet") or "").replace("\n", " ").replace("\r", " ")

                        summary = f"[{ts}] EventID={eid} Record={rec} File={file_name} XML={xml_snippet[:500]}".strip()
                        out_f.write(summary + "\n")

                        text_chunks.append(summary)
                        metadata_list.append({
                            "source": "evtx_raw_fallback",
                            "case_id": case_id,
                            "file": file_name,
                        })
                        wrote_any = True

            if wrote_any:
                print(f"[EVTX] fallback summary rebuild succeeded for case={case_id}")
            else:
                print(f"[EVTX] fallback summary rebuild found no usable content for case={case_id}")

    except Exception as e:
        print(f"[EVTX] fallback summary rebuild failed: {e}")

    # Embed in safe batches
    if text_chunks:
        max_batch = 2000
        total = len(text_chunks)
        for start in range(0, total, max_batch):
            end = min(start + max_batch, total)
            print(f"[EMBED] case={case_id} batch={start}-{end-1} of {total}")
            embed_texts(case_id, text_chunks[start:end], metadata_list[start:end])

    return len(text_chunks)